name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust-version: [1.70, 1.71]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres_pw
          POSTGRES_DB: postgres_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres

      jaeger:
        image: jaegertracing/all-in-one:1.46
        env:
          COLLECTOR_OTLP_ENABLED: true
        ports:
        - "16686:16686"
        - "4317:4317"
  
    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-version }}

    - name: Migrate Database
      run: |
        docker exec -i postgres psql -U postgres -d postgres_db < ./migrations/04102023_init.up.sql

    - name: Build
      run: cargo build --verbose
      env:
        DATABASE_URL: postgres://postgres:postgres_pw@localhost:5432/postgres_db
        JAEGER_URL: http://localhost:4317

    - name: Run tests
      run: cargo test --verbose
      env:
        DATABASE_URL: postgres://postgres:postgres_pw@localhost:5432/postgres_db
        JAEGER_URL: http://localhost:4317
